sudo: required
language: generic

services:
  - docker
  - docker-compose

# before_install:
#   - docker build -t khaalidsubaan/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true sleepingLotus/react-test npm test
# script:
#   - docker-compose up -d

after_success:
  - docker build -t sleepingLotus/chat-web ./client
  - docker build -t sleepingLotus/chat-nginx ./nginx
  - docker build -t sleepingLotus/chat-api ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sleepingLotus/chat-web
  - docker push sleepingLotus/chat-nginx
  - docker push sleepingLotus/chat-api
