version: "3.3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    image: "khaalid-subaan/chat-api-dev:latest"
    container_name: ChatAPI
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    ports:
      - "8030:3000"
    environment:
      - PORT=3000
      - SECRET="secretKey"
      - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
