version: "3.7"
services:
  nginx:
    image: "sleepinglotus/chat-nginx"
    container_name: chat-nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  client:
    image: "sleepinglotus/chat-client"
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3050:3050"
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "sleepinglotus/chat-api"
    container_name: ChatAPI
    ports:
      - "8030:3000"
    environment:
      - PORT=3000
      - SECRET="secretKey"
      - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: "sleepinglotus/chat-mongodb"
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    container_name: mongodb
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
