version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: 'khaalid-subaan/chat-api-dev:latest'
    container_name: ChatAPI
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - SECRET="secretKey"
      - DB=mongodb
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    restart: always
    volumes:
      - /data/db
    ports:
      - '27017:27017'
