version: '3.3'
services:
  nginx:
    image: 'nginx:alpine'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: 'khaalid-subaan/chat-api:latest'
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - SECRET="secretKey"
      - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    restart: always
    volumes:
      - /data/db
    ports:
      - '27017:27017'
